// Main
export const FETCH_BOOK_MAIN='FETCH_FOOD_MAIN'
export const FETCH_BOARD_MAIN='FETCH_BOARD_MAIN'

// Book
export const FETCH_BOOK_LIST='FETCH_BOOK_LIST'
export const FETCH_BOOK_FIND='FETCH_BOOK_FIND'
export const FETCH_BOOK_DETAIL='FETCH_BOOK_DETAIL'

// Board
export const FETCH_BOARD_LIST='FETCH_BOARD_LIST'
export const FETCH_BOARD_PAGE='FETCH_BOARD_PAGE'
export const FETCH_BOARD_DETAIL='FETCH_BOARD_DETAIL'
export const FETCH_BOARD_INSERT='FETCH_BOARD_INSERT'
export const FETCH_BOARD_UPDATE='FETCH_BOARD_UPDATE'
export const FETCH_BOARD_UPDATE_OK='FETCH_BOARD_UPDATE_OK'
export const FETCH_BOARD_DELETE='FETCH_BOARD_DELETE'